version: '3'
services:
  postgres:
    image: 'postgres:13.7-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=twitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
